create_constraint_mode -name default_emulate_constraint_mode -sdc_files [list /dev/null]
create_rc_corner -name default_emulate_rc_corner 
create_rc_corner -name default_emulate_early_rc_corner 
create_rc_corner -name default_emulate_late_rc_corner 
create_library_set -name default_emulate_libset_max -timing [list /home/sos/gpdk/45nm/lan/flow/t1u1/reference_libs/GPDK045/gsclib045_svt_v4.4/gsclib045/timing/slow_vdd1v2_basicCells.lib /home/sos/gpdk/45nm/lan/flow/t1u1/reference_libs/GPDK045/gsclib045_svt_v4.4/gsclib045/timing/slow_vdd1v2_extvdd1v0.lib /home/sos/gpdk/45nm/lan/flow/t1u1/reference_libs/GPDK045/gsclib045_svt_v4.4/gsclib045/timing/slow_vdd1v2_extvdd1v2.lib /home/sos/gpdk/45nm/lan/flow/t1u1/reference_libs/GPDK045/gsclib045_svt_v4.4/gsclib045/timing/slow_vdd1v2_multibitsDFF.lib /home/sos/gpdk/45nm/lan/flow/t1u1/reference_libs/GPDK045/gsclib045_svt_v4.4/gsclib045/timing/slow_vdd1v0_basicCells.lib /home/sos/gpdk/45nm/lan/flow/t1u1/reference_libs/GPDK045/gsclib045_svt_v4.4/gsclib045/timing/slow_vdd1v0_extvdd1v0.lib /home/sos/gpdk/45nm/lan/flow/t1u1/reference_libs/GPDK045/gsclib045_svt_v4.4/gsclib045/timing/slow_vdd1v0_extvdd1v2.lib /home/sos/gpdk/45nm/lan/flow/t1u1/reference_libs/GPDK045/gsclib045_svt_v4.4/gsclib045/timing/slow_vdd1v0_multibitsDFF.lib]
create_library_set -name default_emulate_libset_min -timing [list /home/sos/gpdk/45nm/lan/flow/t1u1/reference_libs/GPDK045/gsclib045_svt_v4.4/gsclib045/timing/slow_vdd1v2_basicCells.lib /home/sos/gpdk/45nm/lan/flow/t1u1/reference_libs/GPDK045/gsclib045_svt_v4.4/gsclib045/timing/slow_vdd1v2_extvdd1v0.lib /home/sos/gpdk/45nm/lan/flow/t1u1/reference_libs/GPDK045/gsclib045_svt_v4.4/gsclib045/timing/slow_vdd1v2_extvdd1v2.lib /home/sos/gpdk/45nm/lan/flow/t1u1/reference_libs/GPDK045/gsclib045_svt_v4.4/gsclib045/timing/slow_vdd1v2_multibitsDFF.lib /home/sos/gpdk/45nm/lan/flow/t1u1/reference_libs/GPDK045/gsclib045_svt_v4.4/gsclib045/timing/slow_vdd1v0_basicCells.lib /home/sos/gpdk/45nm/lan/flow/t1u1/reference_libs/GPDK045/gsclib045_svt_v4.4/gsclib045/timing/slow_vdd1v0_extvdd1v0.lib /home/sos/gpdk/45nm/lan/flow/t1u1/reference_libs/GPDK045/gsclib045_svt_v4.4/gsclib045/timing/slow_vdd1v0_extvdd1v2.lib /home/sos/gpdk/45nm/lan/flow/t1u1/reference_libs/GPDK045/gsclib045_svt_v4.4/gsclib045/timing/slow_vdd1v0_multibitsDFF.lib]
create_delay_corner -name default_emulate_delay_corner -early_library_set default_emulate_libset_min -late_library_set default_emulate_libset_max -rc_corner default_emulate_rc_corner
create_delay_corner -name default_emulate_delay_corner_max -library_set default_emulate_libset_max -rc_corner default_emulate_rc_corner
create_delay_corner -name default_emulate_delay_corner_min -library_set default_emulate_libset_min -rc_corner default_emulate_rc_corner
create_analysis_view -name default_emulate_view -constraint_mode default_emulate_constraint_mode -delay_corner default_emulate_delay_corner
set_analysis_view -setup default_emulate_view -hold default_emulate_view
